server:
  port: 8083

spring:
  application:
    name: borrowing-service

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: tp_group
      topic:
        book: borrowed-book
        user: max-borrowing
    consumer:
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: tp_group
      topic:
        book: book-deleted
        user: user-deleted

  datasource:
    url: jdbc:postgresql://localhost:5432/tp_m1_borrowing
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ubik
  jpa:
    hibernate:
      ddl-auto: update 
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true