server:
  port: 8083

spring:
  application:
    name: borrowing-service

  datasource:
    url: jdbc:postgresql://localhost:5432/tp_m1_borrowing
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ubik
  jpa:
    hibernate:
      ddl-auto: update 
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true